sources = files(
    'stroke_renderer.cpp', 'stroke_mesh_generator.cpp', 'stroke_mesh.cpp',
    'stroke_mesh_renderer.cpp', 'stroke_mesh_outline_renderer.cpp', 'stroke_mesh_collider.cpp', 'trail.cpp'
)

editor_stroke_lib = static_library('stroke', sources,
    dependencies: global_deps,
    link_with: []
)