sources = files(
    'stroke_renderer.cpp', 'stroke_mesh_generator.cpp', 'stroke_mesh.cpp', 'stroke.cpp',
    'stroke_mesh_renderer.cpp', 'stroke_mesh_outline_renderer.cpp', 'stroke_mesh_collider.cpp', 'trail.cpp',
    'stroke_mesh_gl.cpp', 'stroke_renderer_rl.cpp', 'stroke_renderer_gl.cpp', 'stroke_mesh_gl_builder.cpp',
    'stroke_mesh_gl_manager.cpp', 'stroke_mesh_debug_renderer.cpp'
)

editor_stroke_lib = static_library('stroke', sources,
    dependencies: global_deps,
    link_with: []
)